import "./globals.css";
import Providor from "./providor";
import  ConvexClintProvider  from "../app/ConvexClientProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>


        <ConvexClintProvider>
        <Providor>
          {children}
        </Providor>
        </ConvexClintProvider>
      </body>
    </html>
  );
}
