
import "./globals.css";
import Providor from "./providor";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <Providor>
        {children}
        </Providor>

      </body>
    </html>
  );
}
